TOTAL_CARDS: 108

CARDS:
  WILD:
    WILD: 4
    WILD_DRAW_FOUR: 4

  RED:
    ZERO: 1
    ONE: 2
    TWO: 2
    THREE: 2
    FOUR: 2
    FIVE: 2
    SIX: 2
    SEVEN: 2
    EIGHT: 2
    NINE: 2
    SKIP: 2
    REVERSE: 2
    DRAW_TWO: 2

  BLUE:
    ZERO: 1
    ONE: 2
    TWO: 2
    THREE: 2
    FOUR: 2
    FIVE: 2
    SIX: 2
    SEVEN: 2
    EIGHT: 2
    NINE: 2
    SKIP: 2
    REVERSE: 2
    DRAW_TWO: 2

  GREEN:
    ZERO: 1
    ONE: 2
    TWO: 2
    THREE: 2
    FOUR: 2
    FIVE: 2
    SIX: 2
    SEVEN: 2
    EIGHT: 2
    NINE: 2
    SKIP: 2
    REVERSE: 2
    DRAW_TWO: 2

  YELLOW:
    ZERO: 1
    ONE: 2
    TWO: 2
    THREE: 2
    FOUR: 2
    FIVE: 2
    SIX: 2
    SEVEN: 2
    EIGHT: 2
    NINE: 2
    SKIP: 2
    REVERSE: 2
    DRAW_TWO: 2
