ACTIONS:
  - DRAW

  - RED ZERO
  - RED ONE
  - RED TWO
  - RED THREE
  - RED FOUR
  - RED FIVE
  - RED SIX
  - RED SEVEN
  - RED EIGHT
  - RED NINE
  - RED SKIP
  - RED REVERSE
  - RED DRAW_TWO

  - BLUE ZERO
  - BLUE ONE
  - BLUE TWO
  - BLUE THREE
  - BLUE FOUR
  - BLUE FIVE
  - BLUE SIX
  - BLUE SEVEN
  - BLUE EIGHT
  - BLUE NINE
  - BLUE SKIP
  - BLUE REVERSE
  - BLUE DRAW_TWO

  - GREEN ZERO
  - GREEN ONE
  - GREEN TWO
  - GREEN THREE
  - GREEN FOUR
  - GREEN FIVE
  - GREEN SIX
  - GREEN SEVEN
  - GREEN EIGHT
  - GREEN NINE
  - GREEN SKIP
  - GREEN REVERSE
  - GREEN DRAW_TWO

  - YELLOW ZERO
  - YELLOW ONE
  - YELLOW TWO
  - YELLOW THREE
  - YELLOW FOUR
  - YELLOW FIVE
  - YELLOW SIX
  - YELLOW SEVEN
  - YELLOW EIGHT
  - YELLOW NINE
  - YELLOW SKIP
  - YELLOW REVERSE
  - YELLOW DRAW_TWO

  - RED_WILD
  - BLUE_WILD
  - GREEN_WILD
  - YELLOW_WILD

  - RED_WILD_DRAW_FOUR
  - BLUE_WILD_DRAW_FOUR
  - GREEN_WILD_DRAW_FOUR
  - YELLOW_WILD_DRAW_FOUR
